// <auto-generated />
namespace Board.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241954354_1migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
